#!/bin/bash
# Quick start guide for image compression

echo "🖼️  BublikStudios Image Compression Setup"
echo "==========================================="
echo ""
echo "Now that imports are updated, here's what to do next:"
echo ""
echo "STEP 1: Install sharp (image processing library)"
echo "-------"
echo "  cd frontend"
echo "  npm install --save-dev sharp"
echo ""
echo "STEP 2: Run the compression script"
echo "-------"
echo "  npm run compress-images"
echo ""
echo "This will:"
echo "  ✅ Convert PNG/JPG → WebP (50-95% smaller)"
echo "  ✅ Resize to max 1200px (still looks perfect)"
echo "  ✅ Remove metadata (save more bytes)"
echo "  ✅ Show you the savings"
echo ""
echo "Expected output:"
echo "  47 MB → 2 MB (95% reduction)"
echo ""
echo "STEP 3: Build & test"
echo "-------"
echo "  npm run build            # Should compile fine"
echo "  npm run dev              # Test locally"
echo ""
echo "STEP 4: Commit & push"
echo "-------"
echo "  git add ."
echo "  git commit -m 'perf: compress images PNG/JPG → WebP, reduce 47MB → 2MB'"
echo "  git push"
echo ""
echo "STEP 5: Deploy"
echo "-------"
echo "  Push triggers GitHub Actions:"
echo "  → Rebuilds frontend with WebP images"
echo "  → Deploys to your Linux server"
echo "  → Your site loads 10-20x faster! 🚀"
echo ""
echo "==========================================="
echo "Questions? Read: frontend/IMAGE_COMPRESSION.md"
echo ""

