services:
  mysql:
    image: mysql:8.0
    container_name: bublik-mysql
    restart: always
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: bublik
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}

    volumes:
      - /home/bublik/mysql-data:/var/lib/mysql
    
    networks:
      - bublik-network

networks:
  bublik-network:
    external: true
